/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : PDF Document
 #	author : miyako
 #	2017/10/13
 #
 # --------------------------------------------------------------------------------*/

#import <Quartz/Quartz.h>

// --- PDF Document
void PDF_GET_DOCUMENT_ATTRIBUTES(sLONG_PTR *pResult, PackagePtr pParams);
void PDF_SET_DOCUMENT_ATTRIBUTES(sLONG_PTR *pResult, PackagePtr pParams);
